import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

// Local Components
import Navbar from "../components/Navbar/Navbar";

// Styles
import s from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Navbar />
      <div className={s.container}>
        <Head>
          <title>SBS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={s.main}></main>

        <footer className={s.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={s.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
