import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { motion } from "framer-motion";

// Local Components
import Navbar from "../components/Navbar/Navbar";
import AnimatedLetters from "../components/AnimatedLetters/AnimatedLetters";

// Styles
import s from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Navbar />
      <div className={s.container}>
        <Head>
          <title>SBS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={s.main}>
          <section className={s.promo}>
            <div className={s.promo__details}>
              <AnimatedLetters title="Brownie" />
              <AnimatedLetters title="#54" />
              <motion.div
                initial={{ opacity: 0, y: 80 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{
                  ease: "easeInOut",
                  duration: 1,
                  delay: 0.4,
                }}
                className="row-col"
              >
                <p>
                  Made w/ special fruits that will gonna make u fly
                  &quot;Gui&ntilde;o Gui&ntilde;o&quot;
                </p>
              </motion.div>
            </div>
            <div className={s.promo__image}>
              <motion.div
                initial={{ opacity: 0, y: 80 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{
                  ease: "easeInOut",
                  duration: 1,
                  delay: 0.4,
                }}
                className={s.promo__img__container}
              >
                <img src="/brownie.png" alt="image" width="100%" />
              </motion.div>
            </div>
          </section>
          <div className={s.slogan}>
            <div className={s.slogan__text}>
              <h1>
                <span>A Good Day</span>
                <span>To Have</span>
                <span>A Good Day</span>
                <span>To Have</span>
                <span>A Good Day</span>
              </h1>
            </div>
            <div className={`${s.slogan__text} ${s.slogan__text2}`}>
              <h1>
                <span>A Good Day</span>
                <span>To Have</span>
                <span>A Good Day</span>
                <span>To Have</span>
                <span>A Good Day</span>
              </h1>
            </div>
          </div>
        </main>

        <footer className={s.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={s.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
